# Site settings
title: Aspen Roots Development
email: jsturtevant@gmail.com	
description: "Developing software from the roots up."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: aspenwilder
github_username:  jsturtevant

# Build settings
markdown: kramdown
permalink: pretty
