# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Aspen Roots Development
tagline:          'Developing software from the roots up.'
description:      'need to come up with something.'
url:              http://jsturtevant.github.io
author:
  name:           'James Sturtevant'
  url:            https://twitter.com/aspenwilder

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/jsturtevant