# Dependencies
markdown:         kramdown

# Permalinks
permalink:        posts/:title/

# Setup
title:            James Sturtevant
tagline:          ''
description:      ''
url:              https://jamessturtevant.com
author:
  name:           'James Sturtevant'
twitter_username: aspenwilder
github_username:  jsturtevant
rss_feed:         feed.xml
paginate:         5
disqus_shortname: aspenrootsdevelopment
gems:             [jekyll-paginate]
