# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        posts/:title

# Setup
title:            Aspen Roots Development
tagline:          'Developing software from the roots up.'
description:      'need to come up with something.'
url:              http://jsturtevant.github.io
author:
  name:           'James Sturtevant'
twitter_username: aspenwilder
github_username:  jsturtevant
paginate:         5
