# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        posts/:title

# Setup
title:            James Sturtevant
tagline:          ''
description:      ''
url:              http://jsturtevant.github.io
author:
  name:           'James Sturtevant'
twitter_username: aspenwilder
github_username:  jsturtevant
rss_feed:         atom.xml
paginate:         5
disqus_shortname: aspenrootsdevelopment
